import type { Booking, Client, Driver, Partner } from './types';

export const clients: Client[] = [
  { id: 'client-1', name: 'Alice Johnson', phone: '111-222-3333', email: 'alice@corp.com', company: 'MegaCorp', notes: 'Prefers quiet rides, always has luggage.' },
  { id: 'client-2', name: 'Bob Williams', phone: '444-555-6666', email: 'bob@tech.io', company: 'Innovate Inc.', notes: 'Often requires a child seat.' },
];

export const partners: Partner[] = [
  { id: 'partner-1', name: 'Grand Hyatt Hotel', contactPerson: 'Eve', email: 'concierge@hyatt.com', phone: '777-888-9999', commissionRate: 10, bookingsCount: 15, totalCommissionPaid: 2500 },
];

export const drivers: Driver[] = [
  {
    id: 'driver-1',
    name: 'John Doe',
    phone: '123-456-7890',
    email: 'john.doe@example.com',
    avatarUrl: 'https://picsum.photos/seed/driver1/100/100',
    status: 'online',
    performance: { completedJobs: 120, onTimePercent: 98, lastMonthEarnings: 5200 },
  },
  {
    id: 'driver-2',
    name: 'Jane Smith',
    phone: '098-765-4321',
    email: 'jane.smith@example.com',
    avatarUrl: 'https://picsum.photos/seed/driver2/100/100',
    status: 'offline',
    performance: { completedJobs: 85, onTimePercent: 95, lastMonthEarnings: 4300 },
  },
    {
    id: 'driver-3',
    name: 'Mike Johnson',
    phone: '555-666-7777',
    email: 'mike.j@example.com',
    avatarUrl: 'https://picsum.photos/seed/driver3/100/100',
    status: 'online',
    performance: { completedJobs: 210, onTimePercent: 99, lastMonthEarnings: 7100 },
  },
];

export const bookings: Booking[] = [
  {
    id: 'booking-1',
    clientId: 'client-1',
    client: clients[0],
    pickupLocation: '123 Main St, Anytown, USA',
    dropoffLocation: 'Anytown Airport (ATW)',
    pickupTime: new Date(Date.now() + 2 * 60 * 60 * 1000), // 2 hours from now
    status: 'pending_admin',
    createdByRole: 'partner',
    createdById: 'partner-1',
    partner: partners[0],
    createdAt: new Date(),
    notes: 'Client has 2 large suitcases.',
    price: 150,
    commissionDriver: 70,
    commissionPartner: 10,
  },
  {
    id: 'booking-2',
    clientId: 'client-2',
    client: clients[1],
    driverId: 'driver-1',
    driver: drivers[0],
    pickupLocation: '456 Oak Ave, Anytown, USA',
    dropoffLocation: 'Grand Theater',
    pickupTime: new Date(Date.now() + 4 * 60 * 60 * 1000), // 4 hours from now
    status: 'assigned',
    createdByRole: 'admin',
    createdById: 'admin-1',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    notes: 'Child seat requested.',
    price: 80,
    commissionDriver: 75,
    commissionPartner: 0,
  },
  {
    id: 'booking-3',
    clientId: 'client-1',
    client: clients[0],
    driverId: 'driver-2',
    driver: drivers[1],
    pickupLocation: 'Anytown Airport (ATW)',
    dropoffLocation: '789 Pine Ln, Anytown, USA',
    pickupTime: new Date(Date.now() - 24 * 60 * 60 * 1000),
    status: 'completed',
    createdByRole: 'admin',
    createdById: 'admin-1',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
    notes: '',
    price: 120,
    commissionDriver: 70,
    commissionPartner: 0,
  },
  {
    id: 'booking-4',
    clientId: 'client-2',
    client: clients[1],
    driverId: 'driver-1',
    driver: drivers[0],
    pickupLocation: 'Innovate Inc. HQ',
    dropoffLocation: 'The Steakhouse',
    pickupTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    status: 'confirmed',
    createdByRole: 'admin',
    createdById: 'admin-1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    notes: 'Dinner reservation at 8 PM.',
    price: 200,
    commissionDriver: 75,
    commissionPartner: 0,
  },
  {
    id: 'booking-5',
    clientId: 'client-1',
    client: clients[0],
    pickupLocation: 'Grand Hyatt Hotel',
    dropoffLocation: 'Museum of Modern Art',
    pickupTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    status: 'approved',
    createdByRole: 'admin',
    createdById: 'admin-1',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    notes: 'Return trip might be needed.',
    price: 95,
    commissionDriver: 70,
    commissionPartner: 0,
  },
];
